export const COMPANY_LIST_REQUEST = "COMPANY_LIST_REQUEST";
export const COMPANY_LIST_SUCCESS = "COMPANY_LIST_SUCCESS";
export const COMPANY_LIST_FAIL = "COMPANY_LIST_FAIL";

export const COMPANY_ADD_REQUEST = "COMPANY_ADD_REQUEST";
export const COMPANY_ADD_SUCCESS = "COMPANY_ADD_SUCCESS";
export const COMPANY_ADD_FAIL = "COMPANY_ADD_FAIL";

export const COMPANY_DELETE_REQUEST = "COMPANY_DELETE_REQUEST";
export const COMPANY_DELETE_SUCCESS = "COMPANY_DELETE_SUCCESS";
export const COMPANY_DELETE_FAIL = "COMPANY_DELETE_FAIL";
