export const EXPERIENCE_LIST_REQUEST = "EXPERIENCE_LIST_REQUEST";
export const EXPERIENCE_LIST_SUCCESS = "EXPERIENCE_LIST_SUCCESS";
export const EXPERIENCE_LIST_FAIL = "EXPERIENCE_LIST_FAIL";

export const EXPERIENCE_ADD_REQUEST = "EXPERIENCE_ADD_REQUEST";
export const EXPERIENCE_ADD_SUCCESS = "EXPERIENCE_ADD_SUCCESS";
export const EXPERIENCE_ADD_FAIL = "EXPERIENCE_ADD_FAIL";

export const EXPERIENCE_DELETE_REQUEST = "EXPERIENCE_DELETE_REQUEST";
export const EXPERIENCE_DELETE_SUCCESS = "EXPERIENCE_DELETE_SUCCESS";
export const EXPERIENCE_DELETE_FAIL = "EXPERIENCE_DELETE_FAIL";
