export const INTERVIEW_LIST_REQUEST = "INTERVIEW_LIST_REQUEST";
export const INTERVIEW_LIST_SUCCESS = "INTERVIEW_LIST_SUCCESS";
export const INTERVIEW_LIST_FAIL = "INTERVIEW_LIST_FAIL";

export const INTERVIEW_ADD_REQUEST = "INTERVIEW_ADD_REQUEST";
export const INTERVIEW_ADD_SUCCESS = "INTERVIEW_ADD_SUCCESS";
export const INTERVIEW_ADD_FAIL = "INTERVIEW_ADD_FAIL";

export const INTERVIEW_DELETE_REQUEST = "INTERVIEW_DELETE_REQUEST";
export const INTERVIEW_DELETE_SUCCESS = "INTERVIEW_DELETE_SUCCESS";
export const INTERVIEW_DELETE_FAIL = "INTERVIEW_DELETE_FAIL";
