export const PROFILE_LIST_REQUEST = "PROFILE_LIST_REQUEST";
export const PROFILE_LIST_SUCCESS = "PROFILE_LIST_SUCCESS";
export const PROFILE_LIST_FAIL = "PROFILE_LIST_FAIL";

export const PROFILE_ADD_REQUEST = "PROFILE_ADD_REQUEST";
export const PROFILE_ADD_SUCCESS = "PROFILE_ADD_SUCCESS";
export const PROFILE_ADD_FAIL = "PROFILE_ADD_FAIL";

export const PROFILE_DELETE_REQUEST = "PROFILE_DELETE_REQUEST";
export const PROFILE_DELETE_SUCCESS = "PROFILE_DELETE_SUCCESS";
export const PROFILE_DELETE_FAIL = "PROFILE_DELETE_FAIL";
