export const TEAM_LIST_REQUEST = "TEAM_LIST_REQUEST";
export const TEAM_LIST_SUCCESS = "TEAM_LIST_SUCCESS";
export const TEAM_LIST_FAIL = "TEAM_LIST_FAIL";

export const TEAM_ADD_REQUEST = "TEAM_ADD_REQUEST";
export const TEAM_ADD_SUCCESS = "TEAM_ADD_SUCCESS";
export const TEAM_ADD_FAIL = "TEAM_ADD_FAIL";

export const TEAM_DELETE_REQUEST = "TEAM_DELETE_REQUEST";
export const TEAM_DELETE_SUCCESS = "TEAM_DELETE_SUCCESS";
export const TEAM_DELETE_FAIL = "TEAM_DELETE_FAIL";
